#!/bin/bash

# Store list of staged files
STAGED_PHP=$(git diff --cached --name-only --diff-filter=d | grep ".php$" || true)
STAGED_JS_TS=$(git diff --cached --name-only --diff-filter=d | grep -E "\.(js|jsx|ts|tsx|scss)$" || true)

# Format PHP files
if [ -n "$STAGED_PHP" ]; then
    echo "🔍 Formatting PHP files..."
    echo "$STAGED_PHP" | xargs ./vendor/bin/pint
    echo "$STAGED_PHP" | xargs git add
fi

# Format JS/TS/SCSS files
if [ -n "$STAGED_JS_TS" ]; then
    echo "🔍 Formatting JS/TS/SCSS files..."
    echo "$STAGED_JS_TS" | xargs npm run format:staged
    echo "$STAGED_JS_TS" | xargs git add
fi

exit 0