/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "altcha-challenge": [],
    "home": [],
    "dashboard": [],
    "users.index": [],
    "users.create": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.restore": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "login": [],
    "logout": []
}
}
export {};
