#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
    routers:
        chatbot-backoffice-web-80-http:
            entrypoints:
                - http-8080
            rule: HostRegexp(`^chatbot-backoffice\.ddev\.site$`)

            service: 'chatbot-backoffice-web-80'
            ruleSyntax: v3
            tls: false
            # middlewares:
            #   - "chatbot-backoffice-redirectHttps"
        chatbot-backoffice-web-8025-http:
            entrypoints:
                - http-8025
            rule: HostRegexp(`^chatbot-backoffice\.ddev\.site$`)

            service: 'chatbot-backoffice-web-8025'
            ruleSyntax: v3
            tls: false
            # middlewares:
            #   - "chatbot-backoffice-redirectHttps"
        chatbot-backoffice-web-5179-http:
            entrypoints:
                - http-5178
            rule: HostRegexp(`^chatbot-backoffice\.ddev\.site$`)

            service: 'chatbot-backoffice-web-5179'
            ruleSyntax: v3
            tls: false
            # middlewares:
            #   - "chatbot-backoffice-redirectHttps"

        chatbot-backoffice-web-80-https:
            entrypoints:
                - http-8443
            rule: HostRegexp(`^chatbot-backoffice\.ddev\.site$`)

            service: 'chatbot-backoffice-web-80'
            ruleSyntax: v3

            tls: true

        chatbot-backoffice-web-8025-https:
            entrypoints:
                - http-8026
            rule: HostRegexp(`^chatbot-backoffice\.ddev\.site$`)

            service: 'chatbot-backoffice-web-8025'
            ruleSyntax: v3

            tls: true

        chatbot-backoffice-web-5179-https:
            entrypoints:
                - http-5179
            rule: HostRegexp(`^chatbot-backoffice\.ddev\.site$`)

            service: 'chatbot-backoffice-web-5179'
            ruleSyntax: v3

            tls: true

    middlewares:
        chatbot-backoffice-redirectHttps:
            redirectScheme:
                scheme: https
                permanent: true

    services:
        chatbot-backoffice-web-80:
            loadbalancer:
                servers:
                    - url: http://ddev-chatbot-backoffice-web:80

        chatbot-backoffice-web-8025:
            loadbalancer:
                servers:
                    - url: http://ddev-chatbot-backoffice-web:8025

        chatbot-backoffice-web-5179:
            loadbalancer:
                servers:
                    - url: http://ddev-chatbot-backoffice-web:5179

tls:
    certificates:
        - certFile: /mnt/ddev-global-cache/traefik/certs/chatbot-backoffice.crt
          keyFile: /mnt/ddev-global-cache/traefik/certs/chatbot-backoffice.key
