#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
    routers:
        laradev-web-80-http:
            entrypoints:
                - http-8080
            rule: HostRegexp(`^laradev\.ddev\.site$`)

            service: 'laradev-web-80'
            ruleSyntax: v3
            tls: false
            # middlewares:
            #   - "laradev-redirectHttps"
        laradev-web-8025-http:
            entrypoints:
                - http-8025
            rule: HostRegexp(`^laradev\.ddev\.site$`)

            service: 'laradev-web-8025'
            ruleSyntax: v3
            tls: false
            # middlewares:
            #   - "laradev-redirectHttps"
        laradev-web-5179-http:
            entrypoints:
                - http-5178
            rule: HostRegexp(`^laradev\.ddev\.site$`)

            service: 'laradev-web-5179'
            ruleSyntax: v3
            tls: false
            # middlewares:
            #   - "laradev-redirectHttps"

        laradev-web-80-https:
            entrypoints:
                - http-8443
            rule: HostRegexp(`^laradev\.ddev\.site$`)

            service: 'laradev-web-80'
            ruleSyntax: v3

            tls: true

        laradev-web-8025-https:
            entrypoints:
                - http-8026
            rule: HostRegexp(`^laradev\.ddev\.site$`)

            service: 'laradev-web-8025'
            ruleSyntax: v3

            tls: true

        laradev-web-5179-https:
            entrypoints:
                - http-5179
            rule: HostRegexp(`^laradev\.ddev\.site$`)

            service: 'laradev-web-5179'
            ruleSyntax: v3

            tls: true

    middlewares:
        laradev-redirectHttps:
            redirectScheme:
                scheme: https
                permanent: true

    services:
        laradev-web-80:
            loadbalancer:
                servers:
                    - url: http://ddev-laradev-web:80

        laradev-web-8025:
            loadbalancer:
                servers:
                    - url: http://ddev-laradev-web:8025

        laradev-web-5179:
            loadbalancer:
                servers:
                    - url: http://ddev-laradev-web:5179

tls:
    certificates:
        - certFile: /mnt/ddev-global-cache/traefik/certs/laradev.crt
          keyFile: /mnt/ddev-global-cache/traefik/certs/laradev.key
