name: ddev-laradev-react
services:
  db:
    build:
      context: /home/paul/dev/scify/laradev-react/.ddev/.dbimageBuild
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ddev/ddev-dbserver-mysql-8.0:v1.25.1
        gid: "1000"
        uid: "1000"
        username: paul
    cap_add:
      - SYS_NICE
    command: []
    container_name: ddev-laradev-react-db
    environment:
      BITNAMI_VOLUME_DIR: /bitnami/mysql
      COLUMNS: "80"
      DDEV_DATABASE: mysql:8.0
      DDEV_DATABASE_FAMILY: mysql
      DDEV_GID: "1000"
      DDEV_GOARCH: amd64
      DDEV_GOOS: linux
      DDEV_HOSTNAME: laradev-react.ddev.site
      DDEV_PHP_VERSION: "8.4"
      DDEV_PRIMARY_URL: https://laradev-react.ddev.site:8443
      DDEV_PRIMARY_URL_PORT: "8443"
      DDEV_PRIMARY_URL_WITHOUT_PORT: https://laradev-react.ddev.site
      DDEV_PROJECT: laradev-react
      DDEV_PROJECT_TYPE: laravel
      DDEV_ROUTER_HTTP_PORT: "8080"
      DDEV_ROUTER_HTTPS_PORT: "8443"
      DDEV_SCHEME: https
      DDEV_SITENAME: laradev-react
      DDEV_TLD: ddev.site
      DDEV_UID: "1000"
      DDEV_USER: paul
      DDEV_VERSION: v1.25.1
      DOCKER_IP: 127.0.0.1
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      IS_DDEV_PROJECT: "true"
      LINES: "24"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/laradev-react-db/mysql_history
      PGDATABASE: db
      PGHOST: 127.0.0.1
      PGPASSWORD: db
      PGUSER: db
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      TZ: Europe/Berlin
      USER: paul
    extra_hosts:
      - host.docker.internal=host-gateway
    hostname: laradev-react-db
    healthcheck:
      test:
        - CMD-SHELL
        - /healthcheck.sh
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 2m0s
      start_interval: 1s
    image: ddev/ddev-dbserver-mysql-8.0:v1.25.1-laradev-react-built
    labels:
      com.ddev.app-type: laravel
      com.ddev.approot: /home/paul/dev/scify/laradev-react
      com.ddev.platform: ddev
      com.ddev.site-name: laradev-react
    networks:
      ddev_default: null
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 3306
        protocol: tcp
    restart: "no"
    stop_grace_period: 1m0s
    user: 1000:1000
    volumes:
      - type: volume
        source: database
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: /home/paul/dev/scify/laradev-react/.ddev
        target: /mnt/ddev_config
        bind: {}
      - type: bind
        source: /home/paul/dev/scify/laradev-react/.ddev/db_snapshots
        target: /mnt/snapshots
        bind: {}
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
    working_dir: /home/paul
  web:
    build:
      context: /home/paul/dev/scify/laradev-react/.ddev/.webimageBuild
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ddev/ddev-webserver:v1.25.1
        DDEV_DATABASE: mysql:8.0
        DDEV_PHP_VERSION: "8.4"
        gid: "1000"
        uid: "1000"
        username: paul
    cap_add:
      - SYS_PTRACE
    command:
      - /pre-start.sh
    container_name: ddev-laradev-react-web
    environment:
      COLUMNS: "80"
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      COREPACK_HOME: /mnt/ddev-global-cache/corepack
      DDEV_APPROOT: /var/www/html
      DDEV_COMPOSER_ROOT: /var/www/html
      DDEV_DATABASE: mysql:8.0
      DDEV_DATABASE_FAMILY: mysql
      DDEV_DOCROOT: public
      DDEV_FILES_DIR: ""
      DDEV_FILES_DIRS: ""
      DDEV_GID: "1000"
      DDEV_GOARCH: amd64
      DDEV_GOOS: linux
      DDEV_HOSTNAME: laradev-react.ddev.site
      DDEV_MUTAGEN_ENABLED: "false"
      DDEV_PHP_VERSION: "8.4"
      DDEV_PRIMARY_URL: https://laradev-react.ddev.site:8443
      DDEV_PRIMARY_URL_PORT: "8443"
      DDEV_PRIMARY_URL_WITHOUT_PORT: https://laradev-react.ddev.site
      DDEV_PROJECT: laradev-react
      DDEV_PROJECT_TYPE: laravel
      DDEV_ROUTER_HTTP_PORT: "8080"
      DDEV_ROUTER_HTTPS_PORT: "8443"
      DDEV_SCHEME: https
      DDEV_SITENAME: laradev-react
      DDEV_TLD: ddev.site
      DDEV_UID: "1000"
      DDEV_USER: paul
      DDEV_VERSION: v1.25.1
      DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
      DDEV_WEBSERVER_TYPE: nginx-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DDEV_XHPROF_MODE: xhgui
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: public
      DRUSH_OPTIONS_URI: https://laradev-react.ddev.site:8443
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      HTTP_EXPOSE: 8080:80,8025:8025,5178:5179
      HTTPS_EXPOSE: 8443:80,8026:8025,5179:5179
      IS_DDEV_PROJECT: "true"
      LINES: "24"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/laradev-react-web/mysql_history
      NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
      PGDATABASE: db
      PGHOST: db
      PGPASSWORD: db
      PGUSER: db
      PHP_IDE_CONFIG: serverName=laradev-react.ddev.site
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      START_SCRIPT_TIMEOUT: "115"
      TZ: Europe/Berlin
      USER: paul
      VIRTUAL_HOST: laradev-react.ddev.site
      npm_config_cache: /mnt/ddev-global-cache/npm
    expose:
      - "5179"
    extra_hosts:
      - host.docker.internal=host-gateway
    hostname: laradev-react-web
    healthcheck:
      test:
        - CMD-SHELL
        - /healthcheck.sh
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 2m0s
      start_interval: 1s
    image: ddev/ddev-webserver:v1.25.1-laradev-react-built
    labels:
      com.ddev.app-type: laravel
      com.ddev.approot: /home/paul/dev/scify/laradev-react
      com.ddev.platform: ddev
      com.ddev.site-name: laradev-react
    networks:
      ddev_default: null
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 80
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 443
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 5179
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 8025
        protocol: tcp
    restart: "no"
    user: 1000:1000
    volumes:
      - type: bind
        source: /home/paul/dev/scify/laradev-react
        target: /var/www/html
        consistency: cached
      - type: bind
        source: /home/paul/dev/scify/laradev-react/.ddev
        target: /mnt/ddev_config
        read_only: true
        bind: {}
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
      - type: volume
        source: ddev-ssh-agent_socket_dir
        target: /home/.ssh-agent
        volume: {}
    working_dir: /var/www/html/
  xhgui:
    profiles:
      - xhgui
    container_name: ddev-laradev-react-xhgui
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      DDEV_DATABASE_FAMILY: mysql
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      HTTP_EXPOSE: 8143:80
      HTTPS_EXPOSE: 8142:80
      TZ: Europe/Berlin
      VIRTUAL_HOST: laradev-react.ddev.site
      XHGUI_PDO_PASS: db
      XHGUI_PDO_USER: db
      XHGUI_SAVE_HANDLER: pdo
    extra_hosts:
      - host.docker.internal=host-gateway
    healthcheck:
      test:
        - CMD-SHELL
        - /healthcheck.sh
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 2m0s
      start_interval: 1s
    image: ddev/ddev-xhgui:v1.25.1
    labels:
      com.ddev.approot: /home/paul/dev/scify/laradev-react
      com.ddev.site-name: laradev-react
    networks:
      ddev_default: null
      default: null
    restart: "no"
    x-ddev:
      describe-url-port: 'Launch: ddev xhgui'
networks:
  ddev_default:
    name: ddev_default
    external: true
  default:
    name: ddev-laradev-react_default
    labels:
      com.ddev.platform: ddev
volumes:
  database:
    name: laradev-react-mariadb
    external: true
  ddev-global-cache:
    name: ddev-global-cache
    external: true
  ddev-ssh-agent_socket_dir:
    name: ddev-ssh-agent_socket_dir
    external: true
