name: tests

on:
    push:
        branches:
            - develop
            - main
    pull_request:
        branches:
            - develop
            - main

jobs:
    run-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.4
                  tools: composer:v2
                  coverage: xdebug

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Copy Environment File
              run: cp .env.testing .env

            - name: Install Node Dependencies
              run: npm ci

            - name: Build Assets
              run: npm run build

            - name: Install Dependencies
              run: composer install --no-interaction --prefer-dist --optimize-autoloader

            - name: Generate Application Key
              run: |
                  php artisan key:generate --force
                  php artisan config:clear

            - name: Tests
              run: |
                  ./vendor/bin/pest
                  npm run test
